### ISSUE TITLE
Problem while trying to import torch with symsrv.dll (?) on Windows 10

### ISSUE THREAD

**Issue by visar-sorting-dev** [peterjc123/pytorch_dll_load_smoketests#18]
Hello,
I am trying to install Pytorch from source. While the compilation was successful, I am having issues with importing torch on windows 10 with CUDA (using an "old" GPU Quadro K5200). It prints the following error:
```
import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Installations\Pytorch\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 1114] Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué. Error loading "C:\Installations\Pytorch\torch\lib\backend_with_compiler.dll" or one of its dependencies.
```

Therefore, I was redirected here and I tried the command you provided. The debugger stops after trying to import the C:\WINDOWS\SYSTEM32\symsrv.dll, which is not on my machine. The last output lines are:

```
080c:3604 @ 276919921 - LdrLoadDll - ENTER: DLL name: C:\WINDOWS\SYSTEM32\symsrv.dll
080c:3604 @ 276919921 - LdrpLoadDllInternal - ENTER: DLL name: C:\WINDOWS\SYSTEM32\symsrv.dll
080c:3604 @ 276919921 - LdrpFindKnownDll - ENTER: DLL name: symsrv.dll
080c:3604 @ 276919921 - LdrpFindKnownDll - RETURN: Status: 0xc0000135
080c:3604 @ 276919921 - LdrpResolveDllName - ENTER: DLL name: C:\WINDOWS\SYSTEM32\symsrv.dll
080c:3604 @ 276919921 - LdrpResolveDllName - RETURN: Status: 0xc0000135
080c:3604 @ 276919921 - LdrpProcessWork - ERROR: Unable to load DLL: "C:\WINDOWS\SYSTEM32\symsrv.dll", Parent Module: "(null)", Status: 0xc0000135
080c:3604 @ 276919921 - LdrpLoadDllInternal - RETURN: Status: 0xc0000135
080c:3604 @ 276919921 - LdrLoadDll - RETURN: Status: 0xc0000135
(80c.3604): C++ EH exception - code e06d7363 (first chance)
080c:3604 @ 276920234 - LdrpGetProcedureAddress - INFO: Locating procedure "FlsGetValue" by name
(80c.3604): C++ EH exception - code e06d7363 (first chance)
(80c.3604): C++ EH exception - code e06d7363 (!!! second chance !!!)
quit:
```

What should I do to resolve this? Should I simply add it to the System32 folder?

I do not face this issue when installing pytorch (cpu only) via pip. But I want to have Pytorch with cuda.

I thank you in advance for your help

**Comment by peterjc123** [comment]
@visar-sorting-dev Would you please show me the value of the environment variable `PATH`? Also according to https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/symsrv, `symsrv.dll` seems to be a part of the `Debugging Tools for Windows`, which means that your installation may be incomplete.

**Comment by visar-sorting-dev** [comment]
Hello, I thank you for your help. I also see that the error code is e06d7363. Maybe this has nothing to do with symsrv.dll?
Here is the environment variable PATH:

`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\WINDOWS\System32\OpenSSH\;
C:\Program Files\dotnet\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\ProgramData\Tricerat\Plugins\ScrewDrivers\x32\;
C:\ProgramData\Tricerat\Plugins\ScrewDrivers\x64\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.2.0\;
C:\Installations\cudnn-windows-x86_64-8.6.0.163_cuda11-archive\cudnn-windows-x86_64-8.6.0.163_cuda11-archive\bin;
C:\Installations\cudnn-windows-x86_64-8.6.0.163_cuda11-archive\cudnn-windows-x86_64-8.6.0.163_cuda11-archive\include;
C:\Installations\cudnn-windows-x86_64-8.6.0.163_cuda11-archive\cudnn-windows-x86_64-8.6.0.163_cuda11-archive\lib\x64;
C:\Installations\cudnn-windows-x86_64-8.6.0.163_cuda11-archive\cudnn-windows-x86_64-8.6.0.163_cuda11-archive;

C:\Program Files\CMake\bin;
C:\Program Files\7-Zip;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\extras\CUPTI\lib64;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include;
C:\Users\m.jotterand\AppData\Local\Programs\Python\Python38\Scripts\;
C:\Users\m.jotterand\AppData\Local\Programs\Python\Python38\;
C:\Users\m.jotterand\AppData\Local\Microsoft\WindowsApps;`

**Comment by visar-sorting-dev** [comment]
I also see now that I have other dll import errors (cudnn64_8.dll, cufft64_10.dll and symsrv.dll). I rerun the debugger and here is the output file.
[output_cdb.txt](https://github.com/peterjc123/pytorch_dll_load_smoketests/files/10110515/output_cdb.txt)

After checking, I have the dll cudnn64_8.dll in the folder of cudnn which is in the path, and I also have the cufft64_10.dll in the CUDA\bin folder which also is in PATH. I just don't have symsrv.dll in system32 but have it in the debugger folder.

**Comment by peterjc123** [comment]
BTW, I don't think `backend_with_compiler.dl` is part of the PyTorch package. Could you please remove that?

**Comment by visar-sorting-dev** [comment]
After removing:
`>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Installations\Pytorch\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 1114] Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué. Error loading "C:\Installations\Pytorch\torch\lib\jitbackend_test.dll" or one of its dependencies.
`

I have the same output from cdb (in any case, see attached file): [output_cdb.txt](https://github.com/peterjc123/pytorch_dll_load_smoketests/files/10115782/output_cdb.txt).

If I continue deleting the dll, I still get the same error:
`OSError: [WinError 1114] Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué. Error loading "C:\Installations\Pytorch\torch\lib\shm.dll" or one of its dependencies.`

And the later dlls are the torch ones.

**Comment by peterjc123** [comment]
`shm.dll` only depends on VS2019 redist. 
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
https://github.com/pytorch/pytorch/blob/master/torch/lib/libshm_windows/CMakeLists.txt#L6

**Comment by visar-sorting-dev** [comment]
I have VS 16.8.5.
In [this](https://docs.nvidia.com/deeplearning/cudnn/pdf/cuDNN-Support-Matrix.pdf), it is recommended to have VS 2017 for cudnn. But on github, it says it is better to have VS 16.8.5. So could it be this? How do I compile cudnn with VS2017 and the rest with the same VS2019?

**Comment by peterjc123** [comment]
Would you please tell me which commit of PyTorch are you compiling against? Error 1114 refers an actual c++ error(crash) during initialization instead of dll missing.

**Comment by peterjc123** [comment]
> I have VS 16.8.5.
> In [this](https://docs.nvidia.com/deeplearning/cudnn/pdf/cuDNN-Support-Matrix.pdf), it is recommended to have VS 2017 for cudnn. 

Nope, maybe they just forget to add VS2019.

**Comment by peterjc123** [comment]
https://discuss.pytorch.org/t/i-cannot-use-the-pytorch-that-was-built-successfully-from-source-dll-initialization-routine-failed-error-loading-caffe2-detectron-ops-gpu-dll/93243/24?u=peterjc123 maybe useful for you.

**Comment by visar-sorting-dev** [comment]
I have recompiled the master branch from yesterday and still have the same error.
Thank you, I have already seen this thread as I followed the advice to have mkl.

**Comment by peterjc123** [comment]
The master branch won't work for your gpu card Quadro K5200, which has compute capability of 3.5. You'll need to compile for a much older commit.

**Comment by visar-sorting-dev** [comment]
Ok, I thought I had to worry only for the [pre-built packages](https://github.com/moi90/pytorch_compute_capabilities). But then, where can I find the version which would suit me the best?
Thank you for the help

**Comment by visar-sorting-dev** [comment]
Can't I build from source for cc 3.5? For example while specifying TORCH_CUDA_ARCH_LIST?

**Comment by peterjc123** [comment]
> cc 3.5

I'm not sure. It seems PyTorch 1.6 is ok, but I forget when they got rid of cc 3.5 support.

**Comment by peterjc123** [comment]
Looking at https://github.com/pytorch/pytorch/issues/24205, it seems 1.8 is also okay.

**Comment by visar-sorting-dev** [comment]
Thank you very much. I will try that out.
